---
title: "Covid-19 R.M.Campinas"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    social: menu
    navbar:  
      - {title: "Contato", icon: fa-envelope, href: mailto:vinicius.n.o@outlook.com.br }
      - {icon: fa-github, href: https://github.com/vinicius-oliv/ }
    orientation: columns
    includes:
      after_body: footer.html
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(flexdashboard)
library(geobr)
library(sf)
library(tidyverse)
library(plotly)
library(rvest)
library(httr)
library(lubridate)
```

```{r}
#Leitura do banco
casos <- read_csv(file = "covid19_rmc.csv", col_names = T)
```


```{r, cache=T, results = "hide"}
#Shapefile Campinas
rmc <- read_metro_area(2018) %>% filter(name_metro == "RM Campinas")

#
no_axis <- theme(axis.title=element_blank(),
                 axis.text=element_blank(),
                 axis.ticks=element_blank())
```
```{r}
#Função para adicionar casos no dia
add_casos <- function(cidades, quant){
  quant <- as.vector(quant)
  cidades <- as.vector(cidades)
  
  casos <- numeric(20)
  rmc <- as.character(rmc$name_muni)
  
  for(i in 1:length(cidades)){
    for(j in 1:length(rmc)){
      if(cidades[i] == rmc[j]){
        casos[j] <- quant[i]
      }
    }
  }
  return(casos)
}

#Função de cálculo do total de casos(dia X(i) +X(i + 1))
calc_total <- function(novo){
  return(novo + casos$Total[(nrow(casos) - 19): nrow(casos)])
}

#
meses <- c("marco", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro")

#Cálculo para os novos casos (dia X(i + 1) - dia X(i))
calc_novos <- function(atual, dia, mes){
    dia_ant = as.integer(dia) - 1
    mes <- ifelse(dia_ant == 0, 
                  as.integer(mes) - 1, 
                  as.integer(mes)
                  )
    
    if(mes < 10){
      mes = paste0("0", mes)
    }
    
    if(dia_ant == 0 & as.integer(mes) %in% c(1, 3, 5, 6, 8, 10)){
      dia_ant = "31"
    }else if(dia_ant == 0){
      dia_ant = "30"
    }else{
    }
  
    ant <- casos %>% 
               filter(Data == dmy(as.integer(paste0(dia_ant, mes, "2020")))) %>% 
               select(Total)
    
    return(atual - ant[["Total"]])                            
}
```


```{r}
data <- as.character(Sys.Date())

mes <- str_split(data, "-")[[1]][2]

dia <- str_split(data, "-")[[1]][3]

Dia = str_remove(dia, "0")
#Padrão(?) do primeiro dia do mês na url
if(dia == "01"){
  Dia = "1o"
}

Mes <- meses[as.integer(mes) - 2]

#link da cobertura do G1 Campinas, por enquanto se mantém o padrão
url <- paste0("https://g1.globo.com/sp/campinas-regiao/noticia/2020/", mes, "/", dia,                  "/ultimas-noticias-de-coronavirus-de-", Dia, "-de-", Mes,                                        "-na-regiao-de-campinas.ghtml")

texto <- url %>% read_html() %>% html_nodes("ul.content-unordered-list") %>% html_text()

for(i in 1:length(texto)){

  #Garantia de que estou na string contendo as cidades com os casos  
  if(str_detect(texto[i], "Campinas:|Campinas-") == T & 
     str_detect(texto[i], "Valinhos:|Valinhos-") == T){
        cidades <- texto[i]
  }
  
}

#Tratamento da string usando o pacote StringR
casos_cidades <- cidades
cidades <- str_remove_all(cidades, "-.?[[:digit:]]+")
cidades <- str_split(cidades, pattern = " ")[[1]]

if(cidades[1] != "Campinas"){
  cidades <- str_remove_all(casos_cidades, "[[:digit:]]+")
  cidades <- str_split(cidades, pattern = ": ")[[1]]
}

total_casos <- str_extract_all(casos_cidades, "[[:digit:]]+")[[1]]
total_casos <- as.integer(total_casos)

```

```{r}
####### CONF. DE ATUALIZACAO ##########
#Se add_obs = T, então as observações referentes aquele dia serão adicionadas aos dados
#Se add_obs = F, apenas irei atualizar as observações já criadas anteriormente
add_obs = T

if(nrow(casos %>% filter(Data == dmy(paste0(dia, mes, "2020")))) > 0){
  add_obs = F
}

att <- as.logical(add_obs == F)
```


```{r}
#Adiciono as obs. do dia
if(add_obs){
    atual = add_casos(cidades, total_casos)
    
    dat <-as.integer(paste0(dia, mes,"2020"))
    
    casos <- casos %>% 
      add_row(Data = dmy(dat), 
              Cidade = as.character(rmc$name_muni), 
              Novos = calc_novos(atual, dia, mes), 
              Total = atual)
}
```


```{r}
#Atualizo as obs. do dia
if(att){
  
    atual = add_casos(cidades, total_casos)
    
    t <- casos %>% filter(Data == dmy(as.integer(paste0(dia, mes, "2020")))) %>%  
      select(Total)
    
    if(setequal(t$Total, atual) == F){
      dat <-as.integer(paste0(dia, mes,"2020"))
      casos <- casos %>% filter(Data != dmy(dat))
      casos <- casos %>% 
                add_row(Data = dmy(dat), 
                        Cidade = as.character(rmc$name_muni), 
                        Novos = calc_novos(atual, dia, mes), 
                        Total = atual)
    } 
}
```


Column
-----------------------------------------------------------------------

### Total de casos na Região Metropolitana de Campinas

```{r}
#Mapa dos casos por cidade

localizacao <- left_join(rmc, casos, by = c("name_muni" = "Cidade"))

pal <- c("#f6f2cb", "#f9b025","#f98525", "#e76523", "#d44b05")

ultimos_casos <- localizacao %>% filter(Data == dmy(paste0(dia, mes, "2020")))

c <- st_centroid(ultimos_casos$geom)

x = numeric(20)
for(i in 1:length(c)){
  x[i] <- as.numeric(c[[i]])[1]
}

y = numeric(20)
for(i in 1:length(c)){
  y[i] <- as.numeric(c[[i]])[2]
}

ultimos_casos <- ultimos_casos %>% mutate(X = x, Y = y)
ultimos_casos$text <- with(ultimos_casos, paste0("Cidade: ", name_muni, "\nTotal: ", Total))

m <- ggplot(ultimos_casos) +
    geom_sf(aes(fill = Total)) +
    geom_point(aes(x = X, y = Y, text = text), shape = 23, 
               size = 2, fill = "gray90") +
    scale_fill_gradientn(limits = c(0, max(ultimos_casos$Total) + 15),
                         breaks = c(min(ultimos_casos$Total), max(ultimos_casos$Total)),
                         labels = c(as.character(min(ultimos_casos$Total)), 
                                    as.character(max(ultimos_casos$Total))),
                         colors = pal, trans = "sqrt",
                         values = c(seq(0, 1, 0.1))) +
    labs(title = "Casos confirmados por cidade", subtitle= "Região metropolitana de Campinas") +
    guides(fill = guide_colorbar(title = "Nº de casos")) +
    theme_void() +
    no_axis

ggplotly(m, tooltip = "text") %>% 
  layout(hoverlabel = list(font=list(family = "Times",size=18)),
         annotations = list(x = 1, y = 0, text = "Dados: G1 Campinas", 
                       showarrow = F, xref='paper', yref='paper', 
                       xanchor='right', yanchor='auto', xshift=0, yshift=0,
                       font=list(size=15, color="black"))) %>% 
  plotly::config(displayModeBar = F)
```



Column {.tabset}
-------------------------------------

### Evolução por cidade

```{r}
#Plot dos casos por data
k <- casos %>% group_by(Cidade) %>% filter(Total != 0)

p<- ggplot(data = k, aes(x = Data, y = Total, color = Cidade)) +
  geom_line() +
  geom_point()+
  theme_bw()+
  scale_color_brewer(type = "qual", palette = "Paired") +
  scale_y_continuous(breaks=seq(0, max(casos$Total), ceiling(max(casos$Total)/10)),
                     limits = c(0, max(casos$Total)),
                     ) +
  scale_x_date(limit=c(dmy(13032020),casos$Data[nrow(casos)] + 2),
               date_breaks = "2 days",
               date_labels = "%d/%m") +
  labs(title = "Evolução por cidade",
       y = "Casos") +
  guides(color = guide_legend(title = NULL)) +
  theme(axis.title.x =element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position="bottom"
        )
  
ggplotly(p) %>% plotly::config(displayModeBar = F) %>% layout(legend=list(orientation = "h", x = 0, y = -0.2))
```

### Evolução (total)

```{r}
#Plot dos casos por data

totalData <- aggregate(k["Total"], by=k["Data"], sum)

n<- ggplot(data = totalData, aes(x = Data, y = Total)) +
  geom_line(colour = "darkred", size = 1.3) +
  geom_area(fill = "tomato", alpha = .5) +
  geom_point(colour = "darkred", size = 2)+
  theme_bw() +
  scale_color_brewer(type = "qual", palette = "Paired") +
  scale_y_continuous(breaks=seq(0, max(totalData$Total), ceiling(max(totalData$Total)/10)),
                     limits = c(0, max(totalData$Total)),
                     ) +
  scale_x_date(limit=c(dmy(13032020),totalData$Data[nrow(casos)] + 2),
               date_breaks = "2 days",
               date_labels = "%d/%m") +
  labs(title = "Evolução dos casos na RMC",
       y = "Casos") +
  theme(axis.title.x =element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 0.5)
        )
  
ggplotly(n) %>% plotly::config(displayModeBar = F)
```

```{r}
#Atualizo meu banco de dados
write_csv(casos, path = "covid19_rmc.csv")
```

